### ISSUE TITLE
https不友好

### ISSUE THREAD

**Issue by Androad** [JixunMoe/netease-cloud-music-api#1]
v2017.05.22
dalao解析出的地址如果用你博客的前缀对于全站https的会提示mix content，若用真实地址改http头实现https，可以使用，但链接有时效性？隔一段时间会down.

**Comment by jixunmoe** [comment]
网易前段时间加了 HTTPS 好像？到时候可以加个判定自动切换 HTTPS。

链接有时效性，我现在是根据请求获得的 expire 值决定缓存多久。

**Comment by liguge** [comment]
@JixunMoe    http://music.163.com/#/song?id=491484154    这个地址的下架歌曲无法获取歌曲的链接~！

**Comment by jixunmoe** [comment]
@liguge 下架音乐无法获取
