### ISSUE TITLE
赶紧修BUG😂😂😂

### ISSUE THREAD

**Issue by nondanee** [JixunMoe/netease-cloud-music-api#3]
Cookie里带`os=uwp`的骚操作操作被网易发现了😒
```
{
    code:-460
    msg:"Cheating"
}
```
去掉就行了，不过又要灰一片...
~~自己修完跑过了跟大佬说一声~~

**Comment by nondanee** [comment]
那个...大佬能不能把eapi逆向一下🙏
(☆▽☆)

**Comment by jixunmoe** [comment]
有人逆过 Linux 版的，你可以试着移植到 python…

https://gist.github.com/ritayzy/939ff70d2acd3c27262f02fc40778720

这两天有点忙，暂时不会更新… 也有可能之后的版本直接换成 Node 写的版本（不是很熟悉 Python orz...）

**Comment by nondanee** [comment]
谢大佬指点！

你这边写bug超快的啦~
index.py 105行注释掉就就好了了😂
https://github.com/JixunMoe/netease-cloud-music-api/blob/master/index.py#L105
```
headers = {
  'Origin': 'http://music.163.com',
  'X-Real-IP': '118.88.88.88',
  'Accept-Language': 'q=0.8,zh-CN;q=0.6,zh;q=0.2',
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36',
  'Referer': 'http://music.163.com/',
  #'Cookie': 'os=uwp;'
}
```
大佬辛苦

**Comment by jixunmoe** [comment]
这行改了。

移植 Linux API 的话，看周末有没有时间改。

**Comment by jixunmoe** [comment]
鸽了鸽了（。

**Comment by nondanee** [comment]
😂😂😂

**Comment by nondanee** [comment]
那个Linux版的gist我测试过了
```
const Netease = require('./Netease.js')

let netease = new Netease()
netease.song(32507038).then(function(body){
	console.log(body)
})
```
`{"code":-460,"msg":"Cheating"}`

**Comment by nondanee** [comment]
直接上eapi吧，我给你pr，等我有空

**Comment by heroboy** [comment]
@nondanee 用这个 https://github.com/surmon-china/simple-netease-cloud-music/blob/master/src/netease.js

**Comment by nondanee** [comment]
@heroboy 知道了，Cheating是`MUSIC_U`的问题，去掉就好了😂
repo里的我看了，随机取得UA是windows版安卓版和macOS版的，全走linux/forward网易发现不了吗😂
