### ISSUE TITLE
音質無變

### ISSUE THREAD

**Issue by theandychung** [JixunMoe/netease-cloud-music-api#7]
同一個網易雲的連結不管設定極高和普通音質所下載的檔案大小一模一樣
而且都比直接從網易雲(pc)所下載的檔案小
不知道是否有解決辦法？

PS. 可用這個連結來重製這個問題：
http://music.163.com/song?id=431259256
極高和普通音質的檔案大小皆為3.16MB
從網易雲直接下載的大小為7.91MB

**Comment by nondanee** [comment]
您应该是网易云音乐的会员吧
去查了下这首歌比特率128kbps以上的音源 (包括在线收听和下载) 都需要登录并拥有会员权限

![screenshot_20180519-122139](https://user-images.githubusercontent.com/26399680/40265168-c5e1fdaa-5b65-11e8-951e-f3450207f638.png)

服务器的请求是以游客身份发出的
因为没有会员特权，所以在您选择较高比特率时，网易云返回了游客身份下的最高的比特率，即128kbps
这是网易云音乐本身的限制

**Comment by theandychung** [comment]
原來如此
謝謝您的解說
